#ifndef I2C_OPERATIONS_H
#define	I2C_OPERATIONS_H

typedef enum {
    I2C_OPERATION_START,
    I2C_OPERATION_REPEATED_START,
    I2C_OPERATION_STOP,
    I2C_OPERATION_SEND,
    I2C_OPERATION_RECEIVE,
} eI2cOperationType;

typedef enum {
    I2C_OPERATION_RESULT_NONE,
    I2C_OPERATION_RESULT_RUN,
    I2C_OPERATION_RESULT_SUCCESS,
    I2C_OPERATION_RESULT_SUCCESS_ACK,
    I2C_OPERATION_RESULT_SUCCESS_NACK,
    I2C_OPERATION_RESULT_FAILURE,
} eI2cOperationResult;

#endif	/* I2C_OPERATIONS_H */